import Providers from "./providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Imagenet Tree Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-zinc-950 text-emerald-300">
          <div className="mx-auto max-w-5xl p-6">
            <h1 className="text-xl font-semibold mb-4">ImageNet Tree</h1>

            <div className="rounded-xl border border-violet-800 bg-violet-900/20 text-zinc-100 p-2">
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
        
      </body>
    </html>
  );
}
